[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["Alexander B. Ustinov <ustinov@spbau.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
